name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        node-version:
          - "16.x"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci --ignore-scripts
      - run: npm run lint
  test-unit:
    needs: lint
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        node-version:
          - "16.x"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci --ignore-scripts
      - run: npm run test:unit
  test-integration:
    needs: lint
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        node-version:
          - "16.x"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci --ignore-scripts
      - run: npm run test:integration
  test-e2e:
    needs: lint
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        node-version:
          - "16.x"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          npm install
          npm run test:e2e
        env:
          CI: true
  build:
    needs:
      - "test-unit"
      - "test-integration"
      - "test-e2e"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        node-version:
          - "16.x"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci --ignore-scripts
      - run: npm run build --if-present
