name: AWS Redeploy
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: iotakingdoms/actions/packages/aws-redeploy@main
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-north-1
          cluster: iotakingdoms-production
          service: ik-auth-service
