name: Release version
on:
  push:
    tags:
      - "v*"
jobs:
  release-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: iotakingdoms/actions/packages/release-version@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
